# Homework 03

## Due Thursday February 18th

In [2]:
import numpy as np
import time
from numpy.lib import stride_tricks
import glob

### 1. Vector manipulation

Create a vector of zeros of size 10 but have the fifth value be 1.

In [3]:
a = np.zeros(10)  #creating a vector of zeros, size 10
a[4]=1   #Make the 5th value a 1 in the array
print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### 2. Vector range

Create a vector with values ranging from 10 to 49, inclusive.

In [4]:
b = range(10,50)
np.array(b)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element. The API should be

    return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed

Include this (or an equivalent description) in the function's docstring.

In [5]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def reverse(x):
    '''return a 1D vector with the elements reversed
Input x: 1D array
Output res: 1D array, with the elements of `x` reversed'''
    return x[::-1]
x.reverse()  #the numpy method to reverse an array
x

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### 4. Find indices of non-zero elements

Write a function `find_nonzero(x)` that finds the indices of non-zero elements, with an API like

    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices

Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

In [6]:
x = [1, 2, 0, 0, 4, 0]
def find_nonzero(x):
    """return the indices of non-zero elements of an array.
Input: x:  array
Output:indices: array of integer indices"""
    np.nonzero(x==0)[0]
        
print(np.nonzero(x))

(array([0, 1, 4]),)


### 5. Array with random values

Create a 3x3x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.

In [7]:
μ,σ = 0.5,0.1
s = np.random.normal(μ,σ,(3,3,3))
print(s)

[[[ 0.36289058  0.50821503  0.58514704]
  [ 0.44699736  0.3831523   0.52508508]
  [ 0.48015157  0.3576135   0.50419617]]

 [[ 0.49065094  0.35917945  0.65533895]
  [ 0.62533087  0.32848184  0.30971623]
  [ 0.41663994  0.54744966  0.50039771]]

 [[ 0.57323604  0.51182679  0.54207973]
  [ 0.42789641  0.55925738  0.57169183]
  [ 0.51180552  0.43775312  0.57450867]]]


### 6. Operations on an array with random values

Create a 10x10 array with random values. Find 
- the minimum value of the 2nd row
- the maximum value of the 4th column

In [8]:
arr = np.random.randint(100, size=(10, 10))
arr

print(arr)

a = arr[1]
imin = a.argmin()
print(a.min())

x = arr[:, 3]
imax = x.argmax()
print(x.max())

[[89 12  6 47 85 22 74 41 23 25]
 [96 21  1 37 74 97 59 94  3 40]
 [23 93 42 46 25 64 56 44  1 81]
 [ 2 75 85 47 72 66 69 90  4 96]
 [ 5 18 73 99 34 19 95 28 34 42]
 [13 63 58 93 30  8 10 37 25 83]
 [94 58 69 79 30 32 24 53 66 56]
 [84 65 85 98 32 13 21 19 40 62]
 [82 61 90 16  4 60 13 46 23 44]
 [ 0 45 87  1 96 83 38 71  2 81]]
1
99


### 7. Vector without end points

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [9]:
t = np.linspace(0,1,12,endpoint=True)[1:-1]
print(t.reshape(2,5))

[[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545]
 [ 0.54545455  0.63636364  0.72727273  0.81818182  0.90909091]]


### 8. Sorted random vector

Create a random vector of size 10, then sort it.

In [10]:
a = np.random.random(10)
a.sort()
print(a)

[ 0.05904416  0.17525656  0.36851909  0.46595593  0.6184358   0.67973032
  0.72263932  0.7511928   0.80365263  0.97898113]


### 9. Test for array equality

Write a function `is_equal(A, B)` that compare two arrays `A` and `B` and checks to see if they are equal. 

    return True if two arrays are the same shape and all the elements are equal.
    
    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.

The arrays count as equal if they are the same shape and all elements in the array are equal.

In [11]:
a = np.random.random(1)
b = np.random.random(1)

def is_equal(a, b):
    '''return True if two arrays are the same shape and all the elements are equal.

Inputs:
    A, B:  array
Output:
    Bool:  True if A and B have the same shape and identical elements.
'''
    if a.all(a)== a.all(b):
        return True
    else:
        return False
    
print(is_equal(a, b))

True


### 10. Subtract the row mean from rows of a matrix

Create a matrix. Then subtract the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [12]:
a = np.random.rand(4,4) #create a new matrix
b = a - a.mean(axis=1)[:, np.newaxis] #subtracting the mean from the rows

print(a)
print(b)

[[ 0.30907061  0.01683398  0.2225166   0.67605537]
 [ 0.41636318  0.61127945  0.16660843  0.12613216]
 [ 0.7995554   0.15215285  0.76656735  0.64107606]
 [ 0.80463687  0.27930665  0.86807982  0.92715272]]
[[ 0.00295147 -0.28928516 -0.08360254  0.36993623]
 [ 0.08626738  0.28118365 -0.16348737 -0.20396365]
 [ 0.20971748 -0.43768506  0.17672944  0.05123815]
 [ 0.08484285 -0.44048737  0.14828581  0.20735871]]


### 11. Multiply arrays

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [13]:
a = np.random.random((5,5,3))
b = np.random.random((5,5))
c = np.random.random((3,5,5))
b2 = b[:, : , np.newaxis]   #create a new dimension so they arrays can be multiplied, otherwise an array with dimension(5,5,3) and (5,5) cannot be multiplied
solution1 = a * b2  #multiplying array dimension (5,5,3) and (5,5)
solution2 = b * c  #multiplying array dimension (3,5,5) and (5,5) np.dot function can be used for matrix multiplication

print(solution1)
print(solution2)

[[[ 0.32069399  0.47775473  0.26979756]
  [ 0.47592231  0.72672105  0.19003676]
  [ 0.64006238  0.4317965   0.17992534]
  [ 0.1537491   0.67209498  0.53989468]
  [ 0.28336461  0.42688727  0.36571112]]

 [[ 0.23553715  0.43903952  0.11752273]
  [ 0.37099781  0.27779693  0.40436888]
  [ 0.70422073  0.47050649  0.09109345]
  [ 0.10062918  0.00796761  0.61457428]
  [ 0.22543828  0.14456675  0.67399827]]

 [[ 0.09891745  0.0612001   0.06672127]
  [ 0.17156229  0.11848932  0.04591051]
  [ 0.18851828  0.32522839  0.38780128]
  [ 0.62753522  0.01928673  0.57283455]
  [ 0.18143438  0.2950098   0.56323823]]

 [[ 0.6220823   0.12393422  0.27101701]
  [ 0.0186535   0.24564565  0.05349211]
  [ 0.21920657  0.32155806  0.20940026]
  [ 0.24948735  0.17872538  0.13601156]
  [ 0.07515925  0.02377764  0.05552693]]

 [[ 0.64773642  0.48071938  0.07554632]
  [ 0.25911655  0.0285307   0.29085627]
  [ 0.54059944  0.05624855  0.16090765]
  [ 0.06221833  0.09756857  0.02821821]
  [ 0.13441777  0.26377276  0.23

### 12. Creating a new array

Starting with an array

    Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
    
Generate an array 

    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [14]:
z = np.arange(1,15, dtype=np.uint32)
r = stride_tricks.as_strided(z,(11,4),(4,4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 13. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is

    Return equivalent polar coordinates of specified cartesian points.
    
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively


In [15]:
r = np.random.rand(6,2)
def cart2polar(r):
    '''Return equivalent polar coordinates of specified cartesian points.

Inputs:
    xy: array
         Nx2 array of Cartesian coordinates, with columns x and y respectively.

Returns:
    rp: array
        Nx2 array of polar coordinates, with columns radius and angle respectively'''
    x = r[:,0]  # 0 axis
    y = r[:,1]  # 1 axis
    r = np.sqrt(x**2 + y**2)
    theta = np.arctan2(y,x)
    return(r,theta)

cart2polar(r)

(array([ 1.01125477,  0.87544847,  0.37236963,  0.26012134,  1.1283652 ,
         0.19935426]),
 array([ 1.320478  ,  1.27243822,  1.16047282,  1.39309358,  0.68449497,
         0.17412979]))

### 14. Compute and time for loops and array operations.

Calculate the time it takes to do what we did in class

    a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
    b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
    sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

and the time required for doing the same operation with a series of 4 `for` loops, one for each dimension of the arrays. Compare the times by calculating a ratio.

In [16]:
t_start1 = time.time()
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
sol = a * b 

t_stop1 = time.time()
time1 = t_stop1-t_start1

print('{:6.4f} seconds have passed.'.format(t_stop1-t_start1))

#looping over each dimension - a[i,j,k,l]*b[i,j,k,l] a nested loop for i,j,k,l 
t_start2 = time.time()
array = []
#create a new empty array
for i in range(a.shape[0]): #start of a four for loop 
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            for l in range(a.shape[3]):
                array = np.append(array, a[i, j, k, l]*b[i, j, k, l])

array.reshape(4, 8, 16, 2)
t_stop2 = time.time()
time2 = t_stop2-t_start2
print('{:6.4f} seconds have passed.'.format(t_stop2-t_start2))

ratio = time2/time1
print(ratio)

0.0005 seconds have passed.
0.0209 seconds have passed.
42.87909936368086


### 15. Fix the code

This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. Write out what you changed to make it work and why it needed to be changed.

In [17]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa -= (aa/4.) #changed to -=(aa/4)
    #a[:2, :] -= aa remove this line from the code
    t = a.T  #transpose the array so they can be multiplied together

    return (t*b).T 
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

print(res) #printing to check the array

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


### 16. Calculate components of a vector

Read in file `data/burl1h2010.txt`. This file gives a bunch of data from a wind station. In particular, read in the wind direction, `WDIR`, and wind speed, `WSPD`. Then, write a function that calculates and returns the `u` and `v` components of this wind vector, which point along the x- and y-axes.

The function should have the following basic functionality:

    Take in vector and return components.
    
    Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude
        
    Returns:
        u: x component of vector
        v: y component of vector


In [24]:
file = np.loadtxt('burl1h2010.txt')
wind_direction = file[:,5] #input wind direction
wind_speed = file[:,6] #input wind speed
print(wind_direction)#degT
print(wind_speed)#m/s

def wind_vector(vdir,vspd):
        '''Take in vector and return components.

Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

Returns:
    u: x component of vector
    v: y component of vector'''
        u = vspd*(np.cos(vdir))
        v = vspd*(np.sin(vdir))
        return u,v
wind_vector(wind_direction,wind_speed)

print(wind_vector(wind_direction,wind_speed))

[ 134.  123.  130. ...,  147.  152.  150.]
[  3.    3.6   3.3 ...,  11.4  11.9  10.2]
(array([-1.39148661, -3.19668806, -1.21206139, ..., -9.04175518,
        4.27262701,  7.13235823]), array([  2.65777445,  -1.65565257,  -3.06934964, ...,   6.94310185,
        11.10651423,  -7.29173958]))


### 17. (Grad) Write and use a class

Consider one of the data files located in `python4geosciences/data/MCH/`. Write a class, `dataclass`, to store some of the information in the file. The class should:

* be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values found in the file;
* contain a method, `salt_mean`, which returns the mean of the salinity;
* contain a method, `temp_max`, which returns the maximum value of the temperature values.

Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. Instead, write a loop which loops through the file names, reads in the necessary data, calls `dataclass` to store the data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should have a list of all of the class instances, one for each data file. As usage examples, if your list of data objects is called `wind`, you should be able to access the temperatures from the 3rd file that is read in with

    wind[2].temp

and you should be able to calculate the mean salinity of the final file with 

    wind[-1].salt_mean()

Hint: Check out the package `glob` for reading in file names with a wild card. 

In [19]:
#creating a class
class data_class:
    '''Creating a class to store information from the m1007c file'''
    def __init__(self, fname, salinity, temperature):
        self.fname = [fname]
        self.salinity = [salinity]
        self.temperature = [temperature]
    def salt_mean(self):
        '''returns the mean of salinity'''
        return np.mean(self.salinity)
    def temp_max(self):
        '''returns the max value for temperature'''
        return np.max(self.temperature)
    
#loop to go through the files in MCH
CTDdata = [] #empty list
CTD_file = glob.glob('MCH/*.cnv2') #using the glob package to read in file names withs a wild card
for file in CTD_file:
    fname = np.genfromtxt(file, skip_header = 57)
    salinity = fname[:,5]
    temperature = fname[:,2]
    CTDdata.append(data_class(fname,salinity,temperature))

In [20]:
CTDdata[-1].salt_mean()

35.828874999999996

In [21]:
CTDdata[2].temperature

[array([ 21.2128,  21.2149,  21.2177,  21.219 ,  21.2165,  21.2331,
         21.3468,  21.4867,  21.526 ,  21.5914,  21.6244,  21.6219,
         21.6295,  21.6204,  21.6003,  21.5912,  21.4888,  21.3504,
         21.2779,  21.343 ,  21.4117,  21.4415,  21.441 ,  21.3959,
         21.3208,  21.2352,  21.1793,  21.1591,  21.1479,  21.1501,
         21.1435,  21.1413,  21.1385,  21.1377,  21.1369])]

### 18. (Grad) Running mean

Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.

Do not use the `pandas` package or the function `convolve`; instead, use a loop. Use the following API for your function:

    Return the running average of a vector, with averaging window of size N.
    
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
    Outputs:
        out: Vector of running-averaged values; same size as vec


In [22]:
x = np.arange(100) # Create a vector to test the function.

def RunningMean(x, N):
    '''Return the running average of a vector, with averaging window of size N.

Inputs:
    vec: Input vector
    N (int): Averaging window size, or number of elements to include in mean on either side of each element.

Outputs:
    out: Vector of running-averaged values; same size as vec'''
    if N == 0:
        return x
    else:
        cumsum = np.cumsum(np.insert(x, 0, 0)) #cumsum is used to calculate cumulative sum
        return (cumsum[N:] - cumsum[:-N]) / N

print (RunningMean(x,2)) # Test the function using the random vector 
print (RunningMean(x,0)) # Test the function using the random vector x, should return same size as the original vector 

[  0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5  10.5  11.5
  12.5  13.5  14.5  15.5  16.5  17.5  18.5  19.5  20.5  21.5  22.5  23.5
  24.5  25.5  26.5  27.5  28.5  29.5  30.5  31.5  32.5  33.5  34.5  35.5
  36.5  37.5  38.5  39.5  40.5  41.5  42.5  43.5  44.5  45.5  46.5  47.5
  48.5  49.5  50.5  51.5  52.5  53.5  54.5  55.5  56.5  57.5  58.5  59.5
  60.5  61.5  62.5  63.5  64.5  65.5  66.5  67.5  68.5  69.5  70.5  71.5
  72.5  73.5  74.5  75.5  76.5  77.5  78.5  79.5  80.5  81.5  82.5  83.5
  84.5  85.5  86.5  87.5  88.5  89.5  90.5  91.5  92.5  93.5  94.5  95.5
  96.5  97.5  98.5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
