In [2]:
import numpy as np

In [15]:
#1. Vector manipulation: Create a vector of zeros of size 10 but have the fifth value be 1.

a = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
np.array(a)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [17]:
#2.Vector range: Create a vector with values ranging from 10 to 49, inclusive.

b = range(10,50)
np.array(b)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
#3.Reverse a vector: Write a function, reverse(x) which reverses a vector, so that the first element becomes the last
# element. The API should be return a 1D vector with the elements reversed.


x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  #input for the function
np.array(x)

x.reverse()  #Reverse the array
x

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [92]:
#4. Find indices of non-zero elements

s = np.nonzero([1, 2, 0, 0, 4, 0])
print(s)

(array([0, 1, 4]),)


In [64]:
#5. Array with random values: Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

np.random.randint(0.0,1.0, size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [88]:
#6. Operations on an array with random values
#Create a 10x10 array with random values. 
#the minimum value of the 2nd row
#the maximum value of the 4th column

arr = np.random.randint(100, size=(10, 10))
arr

print(arr)

a = arr[1]
imin = a.argmin()
print(a.min())

x = arr[:, 3]
imax = x.argmax()
print(x.max())

[[20 21 78 32 60  9 39 32 43 34]
 [64 74 72 49 23 15 84 26 16 86]
 [69 52 35 83 54 48 99 97 41 85]
 [82 22 30 55  3 46  6 96 91 88]
 [82 64 11  7 89 20 82 71 31 56]
 [99 33 98 64 10 88 40 90 85  6]
 [21  9 74 61 61 77 54 60 23 44]
 [32 45 73  4 85 18 69 64 12 73]
 [59 38 25 47 24 61 27 94 46 72]
 [17 43 42 90 95 52 97 13 43 23]]
15
90


In [104]:
#7. Vector without end points: Create a vector of size 10 with values ranging from 0 to 1, both excluded.

t = np.linspace(0,1,12,endpoint=True)[1:-1]
print(t.reshape(2,5))

[[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545]
 [ 0.54545455  0.63636364  0.72727273  0.81818182  0.90909091]]


In [106]:
#8. Sorted random vector: Create a random vector of size 10, then sort it.

a = np.random.random(10)
a.sort()
print(a)

[ 0.00725824  0.10728225  0.11925037  0.15279048  0.16507856  0.29880183
  0.3405225   0.89641686  0.91996641  0.97912864]


In [118]:
#9. Test for array equality
a = np.random.random(10)
b = np.random.random(7)
print(z)
print(x)



[ 0.65421213  0.6192214   0.85484231  0.1436198   0.46209523  0.70458553
  0.07811607  0.19370711  0.67436069  0.0708469 ]
[ 0.84038554  0.70423799  0.33357224  0.09902427  0.32411954  0.74115093
  0.72239506  0.07527572  0.12824461  0.62477004  0.95229516  0.20266268
  0.48225629  0.7514957   0.86106569]


In [ ]:
#10. Subtract the row mean from rows of a matrix

In [ ]:
#11 Multiply arrays: Multiply an array of dimension (5,5,3) with an array with dimensions (5,5).
#Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [127]:
#12. Creating a new array
#Starting with an array
#Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
#Generate an array
#R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

z = range(1,15)
np.array(z)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [128]:
#13. Convert from Cartesian to polar coordinates
#Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates 
#and return the locations represented in polar coordinates in the same shape matrix. The API is
    #Return equivalent polar coordinates of specified cartesian points.
    #Inputs:
        #xy: array
             #Nx2 array of Cartesian coordinates, with columns x and y respectively.
    #Returns:
        #rp: array
            #Nx2 array of polar coordinates, with columns radius and angle respectively
        
m = np.random.random((5,2))
x,y = m[:,0], m[:,1]
e = np.sqrt(x**2+y**2)
s = np.arctan2(y,x)
print(e)
print(s)

[ 1.04423635  0.64963087  0.48426356  0.69355773  0.46638738]
[ 0.58723651  1.12249592  0.90660837  0.73966476  1.211413  ]


In [ ]:
#14

In [131]:
#15. 15. Fix the code: This code needs to be fixed so that it can run properly and pass the assertion test
#at the bottom. Write out what you changed to make it work and why it needed to be changed.

def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 